spring:
  application:
          name: Resource-application


server:
  port: 0
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
---
spring:
  profiles: local
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.netflix: DEBUG
    org.springframework.retry.support.RetryTemplate: DEBUG


eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
logging.file: logs/product-service.log
---
